/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { SvgIcon, Typography } from "@mui/material";
import CourseCard from "./CourseCard";

interface CategorySectionProps {
  title: string;
}

export const CategorySection: React.FC<CategorySectionProps> = ({ title }) => {
  return (
    <section className="flex flex-col mt-10 w-full max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center max-w-full w-[970px]">
        <div className="flex flex-wrap items-center self-stretch my-auto min-w-[240px] w-[570px] max-md:max-w-full">
          <Typography variant="h3" className="self-stretch my-auto">
            {title}
          </Typography>
          <div className="flex overflow-hidden flex-col justify-center items-center self-stretch p-2.5 my-auto w-9 rounded-lg">
            <SvgIcon className="w-4 min-h-[16px]" />
          </div>
        </div>
        <div className="flex gap-2 items-center self-stretch my-auto">
          <div className="flex overflow-hidden flex-col justify-center items-center self-stretch px-2.5 my-auto w-9 h-9 rounded-lg border border-gray-500 border-solid">
            <SvgIcon className="w-4 min-h-[16px]" />
          </div>
          <div className="flex overflow-hidden flex-col justify-center items-center self-stretch px-2.5 my-auto w-9 h-9 rounded-lg border border-indigo-500 border-solid">
            <SvgIcon className="w-4 min-h-[16px]" />
          </div>
        </div>
      </div>
      <div className="flex gap-4 mt-6 w-full max-md:max-w-full">
        <CourseCard
          imageSrc="image"
          chipLabel="chiplabel"
          chipColor="primary"
          videoCount={19}
          title="tipo"
          tags="Jazz"
          instructor="Andrea Mazzanti"
          type="percorsi"
        />
      </div>
    </section>
  );
};
