/**
 * This code was generated by Builder.io.
 */
import { Accordion, AccordionDetails, AccordionSummary, SvgIcon, Typography } from '@mui/material';
import React from 'react';
// <FILE path="components/Catalog/FilterSection.tsx">

export const FilterSection: React.FC = () => {
  return (
    <div className="flex flex-col py-6 rounded-xl bg-neutral-900 min-w-[240px] w-[264px]">
      <div className="flex-1 shrink self-stretch px-6 w-full text-3xl font-semibold leading-none whitespace-nowrap text-zinc-200 max-md:px-5">
        Filtri
      </div>
      <div className="flex flex-col px-6 mt-6 w-full max-md:px-5">
        <div className="text-lg font-semibold leading-loose text-zinc-200">Livello</div>
        <div className="flex flex-col mt-2 w-full">
          <div className="flex flex-col w-full">
            <div className="flex py-2 pr-11 w-full max-md:pr-5">
              <div className="flex flex-col pt-3 mr-0 w-full">
                <div className="flex items-start pr-11 mt-3 w-full bg-indigo-500 opacity-[0.38] rounded-[100px] max-md:pr-5">
                  <div className="flex z-10 gap-8 justify-between items-start mr-0">
                    <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/89408e0c3ae4fef2bbcf45943b00f466abc88c33a99683f45b18c82ee6bbfa45?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438" alt="" className="object-contain shrink-0 w-0.5 aspect-square rounded-[100px]" />
                    <div className="flex shrink-0 w-0.5 h-0.5 rounded-[100px]" />
                    <div className="flex shrink-0 w-0.5 h-0.5 rounded-[100px]" />
                    <div className="flex shrink-0 w-0.5 h-0.5 rounded-[100px]" />
                    <div className="flex shrink-0 w-0.5 h-0.5 rounded-[100px]" />
                    <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/8d6c7ec0bb8a2be471b300bc58972222aa0b780020094602f5784b1a17d8a772?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438" alt="" className="object-contain shrink-0 w-0.5 aspect-square rounded-[100px]" />
                  </div>
                  <div className="flex shrink-0 h-1.5 bg-indigo-500 rounded-[100px] w-[54px]" />
                </div>
                <div className="flex z-10 flex-col justify-center p-1.5 -mt-4 ml-14 fill-indigo-500 w-[30px] max-md:ml-2.5">
                  <div className="flex shrink-0 w-full h-5 bg-indigo-500 rounded-full fill-indigo-500" />
                </div>
              </div>
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ff6889d62aafd22fe1e03dea4fc58d66aba8bb382125557d5ec92d0c0cea577?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438" alt="" className="object-contain shrink-0 aspect-square fill-indigo-500 w-[30px]" />
            </div>
          </div>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/76dc08acff21c02c1316535684671ade136c8858c72af5f6adfd431208ff6e11?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438" alt="" className="object-contain w-full aspect-[12.05]" />
        </div>
        <Accordion className="mt-6 w-full">
          <Accordion className="w-full">
            <AccordionSummary>
              <Typography variant="body1" className="self-center h-6">
                Genere
              </Typography>
              <div className="flex items-start self-center">
                <SvgIcon className="flex flex-col self-center w-6 max-w-full min-h-[24px]" />
              </div>
            </AccordionSummary>
            <AccordionDetails />
          </Accordion>
          <Accordion className="w-full">
            <AccordionSummary>
              <Typography variant="body1" className="self-center h-6">
                Argomento
              </Typography>
              <SvgIcon className="flex flex-col shrink-0 self-center w-6 h-6" />
            </AccordionSummary>
            <AccordionDetails />
          </Accordion>
          <Accordion className="w-full">
            <AccordionSummary>
              <Typography variant="body1" className="self-center h-6">
                Livello
              </Typography>
              <SvgIcon className="flex flex-col shrink-0 self-center w-6 h-6" />
            </AccordionSummary>
            <AccordionDetails />
          </Accordion>
        </Accordion>
      </div>
    </div>
  );
};