/**
 * This code was generated by Builder.io.
 */
import { FormLabel } from "@mui/material";
import React from "react";

type CategoryItem = {
  image: string;
  label: string;
};

const categories: CategoryItem[] = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/68125f7b17f0dfbb08313d3706267343fa7c5696b295e376db7750b81c434444?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Chitarra",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d0bd63a21e07ff6f5118b0ea03d344cca0f03ad90c853bf3d4643e82ba738a50?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Batteria",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d718cec7e09e7f9ff399a0d7267f1ef26e4e755d3de434fe2065159830135b4b?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Produzione musicale",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/64e77ac1d04991c8b0da6c0fa3ffa20aa26a6d11f93d049b18805e6ac5ae2798?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Piano e tastiera",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/acfa061dbaf63fb8659355e5e9b8806bc6af85d737d6f0733476dd8a0002a56b?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Ukulele",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8b2e3f1db78bda93722238cecd9f1e16b434a2071070cb34d38f219d33fd3880?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    label: "Basso",
  },
];

const CategoryGrid: React.FC = () => {
  return (
    <section className="flex flex-wrap gap-6 items-start w-full max-md:max-w-full">
      {categories.map((category, index) => (
        <div
          key={index}
          className="flex flex-col flex-1 shrink justify-center p-2 rounded-lg border border-solid basis-0 bg-neutral-900 border-neutral-400"
        >
          <div className="flex flex-col w-full">
            <div className="flex flex-col items-center w-full">
              <img
                loading="lazy"
                src={category.image}
                className="object-contain aspect-square w-[72px]"
                alt={category.label}
              />
              <FormLabel className="mt-2">{category.label}</FormLabel>
            </div>
          </div>
        </div>
      ))}
    </section>
  );
};

export default CategoryGrid;
