/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchSection from "./SearchSection";
import FeaturedContent from "./FeaturedContent";
import CategoryGrid from "./CategoryGrid";
import Filters from "./Filters";
import ContentSection from "./ContentSection";
import Layout from "../Layout/Layout";

const featuredContents = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/23cfe8b80c13b21953bc9381f56436ce489439da31cf726a5492e82525d64699?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    type: "Serie",
    title: "Chitarra Rock - Gli assoli",
    level: "Avanzato",
    genre: "Jazz",
    instructor: {
      name: "Giuvazza Maggiore",
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2ff5e90d5f27a3e4a72964cf459acf6c9e7191d453628cfbcf4bf741e726330f?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    videoCount: 19,
    typeColor: "bg-red-500",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0687a76a45c57fd37bbfa8cae7f6bfe33ef2e070a4713e3c5e947175a2cfc87b?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    type: "Percorsi",
    title: "Chitarra da zero",
    level: "Intermedio",
    instructor: {
      name: "Giuvazza Maggiore",
      avatar:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2cc745f42c1620b45b3303c34b52d63a44d9e87153e25ecaecf1a756a2160c78?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    videoCount: 19,
    typeColor: "bg-sky-200",
  },
  // Add more featured content items as needed
];

const latestContents: {
  image: string;
  type: string;
  title: string;
  level: string;
  genre?: string;
  instructor: { name: string; avatar: string };
  videoCount: number;
  typeColor: string;
}[] = [
  // Similar structure as featuredContents, but with different data
];

const popularContents: {
  image: string;
  type: string;
  title: string;
  level: string;
  genre?: string;
  instructor: { name: string; avatar: string };
  videoCount: number;
  typeColor: string;
}[] = [
  // Similar structure as featuredContents, but with different data
];

const staticCategory1Contents: {
  image: string;
  type: string;
  title: string;
  level: string;
  genre?: string;
  instructor: { name: string; avatar: string };
  videoCount: number;
  typeColor: string;
}[] = [
  // Similar structure as featuredContents, but with different data
];

const CategoryPage: React.FC = () => {
  return (
    <Layout isLogged>
      <SearchSection />
      <FeaturedContent />
      <CategoryGrid />
      <div className="flex flex-col mt-10 w-full max-md:max-w-full">
        <div className="flex flex-wrap gap-6 items-start w-full">
          <Filters />
          <div className="flex flex-col flex-1 shrink justify-center basis-0 min-w-[240px] max-md:max-w-full">
            <ContentSection title="In evidenza" contents={featuredContents} />
            <ContentSection title="Ultime uscite" contents={latestContents} />
            <ContentSection title="Più seguiti" contents={popularContents} />
            <ContentSection
              title="Categoria statica 1"
              contents={staticCategory1Contents}
            />
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default CategoryPage;
