/**
 * This code was generated by Builder.io.
 */
import React from "react";

type ContentCardProps = {
  image: string;
  type: string;
  title: string;
  level: string;
  genre?: string;
  instructor: {
    name: string;
    avatar: string;
  };
  videoCount: number;
  typeColor: string;
};

const ContentCard: React.FC<ContentCardProps> = ({
  image,
  type,
  title,
  level,
  genre,
  instructor,
  videoCount,
  typeColor,
}) => {
  return (
    <article className="flex overflow-hidden flex-col flex-1 shrink w-full rounded-2xl basis-0 bg-neutral-900 min-w-[240px]">
      <div className="flex flex-col w-full rounded">
        <div className="flex overflow-hidden relative flex-col justify-between items-start p-2 w-full text-xs font-medium leading-none rounded-2xl min-h-[196px]">
          <img
            loading="lazy"
            src={image}
            className="object-contain z-0 flex-1 self-stretch w-full rounded-xl aspect-[1.68]"
            alt={title}
          />
          <div
            className={`flex overflow-hidden absolute top-4 left-4 z-0 items-center px-1 py-1 whitespace-nowrap ${typeColor} rounded-md min-h-[24px] text-zinc-50`}
          >
            <div className="self-stretch px-1 my-auto">{type}</div>
          </div>
          <div className="flex absolute z-0 items-center p-1 rounded-md bg-gray-600 bg-opacity-70 bottom-[19px] right-[17px] text-zinc-200">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4fd22c77d8e5b303ab9d5f372d1e5bf1985ede6d2d52a36360d533cd6e827e8?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
              className="object-contain shrink-0 self-stretch my-auto w-6 bg-blend-normal aspect-square"
              alt=""
            />
            <div className="self-stretch px-1 py-1 my-auto">
              {videoCount} video
            </div>
          </div>
        </div>
        <div className="flex flex-col px-4 pt-2 pb-4 w-full">
          <div className="flex flex-col w-full rounded-2xl">
            <div className="flex flex-col w-full">
              <h3 className="flex-wrap flex-1 shrink gap-2.5 self-stretch w-full text-2xl font-semibold leading-7 text-zinc-200">
                {title}
              </h3>
              <div className="flex gap-2 items-center mt-2 w-full">
                <div className="flex items-start self-stretch my-auto">
                  <div className="flex overflow-hidden items-center px-1 py-1 rounded-md bg-gray-600 bg-opacity-70 min-h-[24px]">
                    <div className="flex relative flex-col justify-center items-center self-stretch my-auto bg-blend-normal aspect-square w-[18px]">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d51500b79b048037c09ccec4cd14be6c6ec125e1ace47a955c4f25ec40cc40c6?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
                        className="object-cover absolute inset-0 size-full"
                        alt=""
                      />
                      <div className="flex relative w-full min-h-[18px] rotate-[-1.5707963267948966rad]" />
                    </div>
                    <div className="self-stretch px-1 my-auto text-xs font-medium leading-none whitespace-nowrap text-zinc-50">
                      {level}
                    </div>
                  </div>
                </div>
                {genre && (
                  <div className="flex overflow-hidden items-center self-stretch px-1 py-1 my-auto text-xs font-medium leading-none whitespace-nowrap rounded-md border border-solid border-zinc-200 min-h-[24px] text-zinc-200">
                    <div className="self-stretch px-1 my-auto">{genre}</div>
                  </div>
                )}
              </div>
              <div className="flex gap-2 items-center mt-2 w-full">
                <div className="flex relative flex-col justify-center items-center self-stretch my-auto w-8 aspect-square rounded-[100px]">
                  <img
                    loading="lazy"
                    src={instructor.avatar}
                    className="object-cover absolute inset-0 size-full"
                    alt={instructor.name}
                  />
                  <div className="flex relative w-full min-h-[32px] rotate-[-1.5707963267948966rad]" />
                </div>
                <div className="self-stretch my-auto text-xs font-medium leading-none text-zinc-50">
                  {instructor.name}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>
  );
};

export default ContentCard;
