/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ContentCard from "./ContentCard";

type ContentSectionProps = {
  title: string;
  contents: Array<{
    image: string;
    type: string;
    title: string;
    level: string;
    genre?: string;
    instructor: {
      name: string;
      avatar: string;
    };
    videoCount: number;
    typeColor: string;
  }>;
};

const ContentSection: React.FC<ContentSectionProps> = ({ title, contents }) => {
  return (
    <section className="flex flex-col mt-10 w-full max-md:max-w-full">
      <div className="flex flex-wrap gap-10 justify-between items-center max-w-full w-[970px]">
        <h2 className="flex-wrap gap-2.5 self-stretch my-auto text-3xl font-semibold leading-none text-center text-zinc-200">
          {title}
        </h2>
        <div className="flex gap-2 items-center self-stretch my-auto">
          <button
            className="flex overflow-hidden flex-col justify-center items-center self-stretch px-2.5 my-auto w-9 h-9 rounded-lg border border-gray-500 border-solid"
            aria-label="Previous"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4b266372cb29dca50efb61bff1103b96397de38f0c5d8299446c5890b93f8939?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
              className="object-contain w-4 aspect-square"
              alt=""
            />
          </button>
          <button
            className="flex overflow-hidden flex-col justify-center items-center self-stretch px-2.5 my-auto w-9 h-9 rounded-lg border border-indigo-500 border-solid"
            aria-label="Next"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/52d5b0a9233aa544096b2220b4b7be92ea5f1ee94390ced5a74e34d1e14e0809?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
              className="object-contain w-4 aspect-square"
              alt=""
            />
          </button>
        </div>
      </div>
      <div className="flex gap-4 mt-6 w-full max-md:max-w-full">
        {contents.map((content, index) => (
          <ContentCard key={index} {...content} />
        ))}
      </div>
    </section>
  );
};

export default ContentSection;
