/**
 * This code was generated by Builder.io.
 */
import { Button } from "@mui/material";
import React from "react";

const FeaturedContent: React.FC = () => {
  return (
    <section className="flex flex-col justify-center mt-4 w-full max-md:max-w-full">
      <div className="flex flex-wrap w-full rounded-xl bg-neutral-900 min-h-[450px] max-md:max-w-full">
        <div className="flex flex-col flex-1 shrink justify-center px-8 py-10 basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full">
          <div className="flex flex-col w-full max-md:max-w-full">
            <div className="flex overflow-hidden items-center self-center p-1 bg-red-100 rounded-md">
              <div className="flex flex-col justify-center self-stretch px-1.5 py-2 my-auto w-6">
                <div className="flex shrink-0 w-2.5 h-2.5 bg-red-700 rounded-full fill-red-700" />
              </div>
              <div className="self-stretch px-1 py-1 my-auto text-xs font-medium leading-none text-red-700">
                Masterclass Live
              </div>
            </div>
            <h2 className="mt-4 text-4xl font-semibold leading-10 text-center text-zinc-200 max-md:max-w-full">
              Tecniche Melodiche negli Assoli di Chitarra
            </h2>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4abcf3b5ad004c0a02719844c727cc66ecf74909d76abadfd4b9bcd69eba8434?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
              className="object-contain self-center mt-4 w-20 aspect-[40] stroke-[3px] stroke-red-400"
              alt="Decorative line"
            />
            <div className="flex gap-2 justify-center items-center px-4 mt-4 w-full text-lg font-semibold leading-loose text-center rounded-2xl text-zinc-200 max-md:max-w-full">
              <div className="flex-1 shrink self-stretch my-auto w-full min-w-[240px] max-md:max-w-full">
                con Tony De Gruttola
              </div>
            </div>
          </div>
          <div className="flex flex-col self-center mt-8 max-w-full w-[187px]">
            <div className="flex gap-2 justify-center items-center w-full text-sm font-medium leading-none text-center text-zinc-200">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5ebcd9f6c69ff0871f65aaa42b942343720ad0faaebbc7752c535c1045167d6f?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
                className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
                alt=""
              />
              <div className="self-stretch my-auto">22 Settembre - 21:30</div>
            </div>
            <Button
              size="large"
              variant="contained"
              color="primary"
              className="mt-4 w-full"
            >
              Accedi alla live
            </Button>
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/81ba2ff2f482cdc7ab8254d93f7fb0ab94a0d0e4c3a0d8a6f8b4875c84ddeb60?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
          className="object-contain rounded-none aspect-[1.4] min-w-[240px] w-[632px] max-md:max-w-full"
          alt="Featured content visual"
        />
      </div>
      <nav className="flex flex-wrap justify-center items-center mt-4 w-full max-md:max-w-full">
        <button
          className="flex overflow-hidden flex-col justify-center items-center self-stretch p-3.5 my-auto rounded-lg rotate-[1.2246468525851679e-16rad] w-[52px]"
          aria-label="Previous"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b9a82c2f8c81a04aeec1792556ca6c355eb188778d0aa6ffa136742d0940416a?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
            className="object-contain w-6 aspect-square"
            alt=""
          />
        </button>
        <div className="flex gap-2 justify-center items-center self-stretch my-auto">
          <span className="self-stretch my-auto w-4 h-4" aria-hidden="true" />
          <span className="self-stretch my-auto w-4 h-4" aria-hidden="true" />
        </div>
        <button
          className="flex overflow-hidden flex-col justify-center items-center self-stretch p-3.5 my-auto rounded-lg w-[52px]"
          aria-label="Next"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c28ad0110b94431f51aa04b60d9caa4fe4981082ea01d9eb44f5862f17bbd51?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
            className="object-contain w-6 aspect-square"
            alt=""
          />
        </button>
      </nav>
    </section>
  );
};

export default FeaturedContent;
