/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Filters: React.FC = () => {
  return (
    <aside className="flex flex-col py-6 rounded-xl bg-neutral-900 min-w-[240px] w-[264px]">
      <h2 className="flex-1 shrink self-stretch px-6 w-full text-3xl font-semibold leading-none whitespace-nowrap text-zinc-200 max-md:px-5">
        Filtri
      </h2>
      <div className="flex flex-col px-6 mt-6 w-full max-md:px-5">
        <h3 className="text-lg font-semibold leading-loose text-zinc-200">
          Livello
        </h3>
        <div className="flex flex-col mt-2 w-full">
          <div className="flex flex-col w-full">
            <div className="flex py-2 pr-11 w-full max-md:pr-5">
              <div className="flex flex-col pt-3 mr-0 w-full">
                <div className="flex items-start pr-11 mt-3 w-full bg-indigo-500 opacity-[0.38] rounded-[100px] max-md:pr-5">
                  <div className="flex z-10 gap-8 justify-between items-start mr-0">
                    {[...Array(6)].map((_, index) => (
                      <img
                        key={index}
                        loading="lazy"
                        src={`http://b.io/ext_${14 + index}-`}
                        className="object-contain shrink-0 w-0.5 aspect-square rounded-[100px]"
                        alt=""
                      />
                    ))}
                  </div>
                  <div className="flex shrink-0 h-1.5 bg-indigo-500 rounded-[100px] w-[54px]" />
                </div>
                <div className="flex z-10 flex-col justify-center p-1.5 -mt-4 ml-14 fill-indigo-500 w-[30px] max-md:ml-2.5">
                  <div className="flex shrink-0 w-full h-5 bg-indigo-500 rounded-full fill-indigo-500" />
                </div>
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ff6889d62aafd22fe1e03dea4fc58d66aba8bb382125557d5ec92d0c0cea577?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
                className="object-contain shrink-0 aspect-square fill-indigo-500 w-[30px]"
                alt=""
              />
            </div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/76dc08acff21c02c1316535684671ade136c8858c72af5f6adfd431208ff6e11?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
            className="object-contain w-full aspect-[12.05]"
            alt=""
          />
        </div>
      </div>
      <div className="flex flex-col mt-6 w-full">
        {["Genere", "Argomento", "Livello"].map((filter, index) => (
          <div
            key={index}
            className="flex flex-col w-full text-lg font-semibold leading-loose whitespace-nowrap text-zinc-200"
          >
            <div
              className={`flex flex-col justify-center px-6 py-4 w-full bg-neutral-900 ${
                index === 0 ? "rounded-2xl" : ""
              } max-md:px-5`}
            >
              <div className="flex gap-2 items-center w-full">
                <div className="flex-1 shrink self-stretch my-auto h-6">
                  {filter}
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d89ae725c0c2cf4bc2a9752c91b97ff2106c502a7179ef43507b5f5cbd05868?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
                  className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                  alt=""
                />
              </div>
            </div>
          </div>
        ))}
      </div>
    </aside>
  );
};

export default Filters;
