/**
 * This code was generated by Builder.io.
 */
import { Button, Menu } from "@mui/material";
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="relative w-full max-md:max-w-full">
      <Menu open>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5ae4fc78ce27eb66347fe70512f389ce437febd39102a2e3887c419f8e76bec?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
          className="object-contain z-0 shrink-0 self-stretch my-auto aspect-[3.62] w-[152px]"
          alt="Logo"
        />
        <nav className="flex z-0 flex-wrap flex-1 shrink gap-4 items-center self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full">
          <Button
            size="small"
            variant="outlined"
            color="primary"
            className="self-stretch my-auto"
          >
            Accedi
          </Button>
          <Button
            size="small"
            variant="contained"
            color="primary"
            className="self-stretch my-auto"
          >
            Iscriviti
          </Button>
        </nav>
      </Menu>
    </header>
  );
};

export default Header;
