/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex overflow-hidden relative flex-col justify-center items-center bg-zinc-900">
      <Header />
      <main className="flex z-0 flex-1 gap-2.5 justify-center self-center size-full max-md:max-w-full">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
