/**
 * This code was generated by Builder.io.
 */
import { Button, TextField } from "@mui/material";
import React from "react";

const SearchSection: React.FC = () => {
  return (
    <section className="flex relative flex-col p-8 w-full rounded-xl bg-neutral-900 max-md:px-5 max-md:max-w-full">
      <h1 className="z-0 self-center text-5xl font-semibold leading-none text-center text-zinc-200 max-md:max-w-full max-md:text-4xl">
        Esplora il catalogo
      </h1>
      <TextField
        placeholder="Chitarra"
        value="Value"
        variant="filled"
        size="medium"
        className="self-center mt-8 max-w-full w-[900px]"
        InputProps={{}}
      />
      <div className="flex z-0 flex-wrap gap-4 items-start mt-8 w-full text-xs font-medium leading-none text-zinc-50 max-md:max-w-full">
        {[
          "Chitarra",
          "Batteria",
          "Travis Barker",
          "Assolo chitarra",
          "Assolo chitarra",
          "Assolo chitarra",
          "Assolo chitarra",
          "Assolo chitarra",
          "Assolo chitarra",
          "Assolo chitarra",
        ].map((tag, index) => (
          <div
            key={index}
            className="flex overflow-hidden items-center p-1 whitespace-nowrap rounded-md bg-gray-600 bg-opacity-70"
          >
            <div className="self-stretch px-1 py-1 my-auto">{tag}</div>
          </div>
        ))}
      </div>
      <Button
        size="small"
        variant="contained"
        color="primary"
        className="absolute self-start bottom-[102px] right-[187px]"
      >
        Cerca
      </Button>
      <div className="flex overflow-hidden absolute z-0 flex-col justify-center items-center p-2.5 w-9 rounded-lg bottom-[102px] right-[296px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f636b82e96f5654a12c23d8c7511fcdfe92ab728365ae2e336c1ac9588a7d3b6?placeholderIfAbsent=true&apiKey=ab14136582c84aab8af41f16349d0438"
          className="object-contain w-full aspect-square"
          alt=""
        />
      </div>
    </section>
  );
};

export default SearchSection;
