/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ProgressIndicatorProps {
  steps: number;
  currentStep: number;
}

const ProgressIndicator: React.FC<ProgressIndicatorProps> = ({
  steps,
  currentStep,
}) => {
  return (
    <React.Fragment>
      {Array.from({ length: steps }, (_, index) => (
        <div
          key={index}
          className="w-full"
        >
          <div
            className={`flex rounded-3xl min-h-[16px] ${
              index + 1 === currentStep
                ? "bg-indigo-500"
                : "bg-gray-600 bg-opacity-70"
            }`}
          />
        </div>
      ))}
    </React.Fragment>
  );
};

export default ProgressIndicator;
