/**
 * This code was generated by Builder.io.
 */
import {
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
} from "@mui/material";
import React from "react";
interface RadioOptionGroupProps {
  options: string[];
  value: string[];
  labelClass?: string;
  labelPlacement?: "bottom" | "end" | "start" | "top";
}

export const RadioOptionGroup: React.FC<RadioOptionGroupProps> = ({
  options,
  value,
  labelPlacement,
  labelClass,
}) => {
  return (
    <FormControl className="w-full">
      <RadioGroup
        aria-labelledby="demo-radio-buttons-group-label"
        name="radio-buttons-group"
        className="space-y-4 w-full"
      >
        {options.map((option, value) => (
          <div
            className={`w-full py-4 pr-6 border rounded-2xl ${
              /* change style when checked */
              false
                ? "border-primary-main bg-action-focus"
                : "border-action-divider bg-paper"
            }`}
          >
            <FormControlLabel
              value={value}
              control={<Radio />}
              label={option}
              labelPlacement={labelPlacement}
              className={`${labelClass} w-full`}
            />
          </div>
        ))}
      </RadioGroup>
    </FormControl>
  );
};
