/**
 * This code was generated by Builder.io.
 */
import { FormControl, FormControlLabel, Radio, RadioGroup } from "@mui/material";
import React from "react";
interface RadioOptionGroupProps {
  options: string[];
  value: string[];
}

export const RadioOptionGroup: React.FC<RadioOptionGroupProps> = ({
  options,
  value,
}) => {
  return (
    <FormControl>
      <RadioGroup
        aria-labelledby="demo-radio-buttons-group-label"
        name="radio-buttons-group"
        className="space-y-4"
      >
      {options.map((option, value) => (
        <div className={`py-4 pr-4 border rounded-2xl ${
              false
                ? "border-primary-main bg-action-focus"
                : "border-action-divider bg-default"
            }`}>
           <FormControlLabel
            value={value}
            control={<Radio />}
            label={option}
            labelPlacement="start"
            className="m-0"
          />
        </div>
      ))}
      </RadioGroup>
    </FormControl>
  );
};
