/**
 * This code was generated by Builder.io.
 */
import { Radio } from "@mui/material";
import CheckedIcon from '@mui/icons-material';
import React from "react";

interface SessionOptionProps {
  id: number;
  label: string;
  imageSrc: string;
  isSelected?: boolean;
}

const SessionOption: React.FC<SessionOptionProps> = ({
  id,
  label,
  imageSrc,
  isSelected = false,
}) => {
  return (
    <div
      className={`flex flex-col flex-1 shrink justify-center items-center px-2 rounded-lg basis-0 ${
        isSelected ? "bg-zinc-700" : "bg-neutral-900"
      } h-[148px] w-[148px]`}
    >
      <div className="flex flex-col w-full">
        <Radio
          color="primary"
          size="small"
          className="self-end w-4"
          checkedIcon={isSelected ? <div>ciao</div> : undefined}
        />
        <div className="flex flex-col items-center w-full text-base font-semibold text-zinc-200">
          <img
            loading="lazy"
            src={imageSrc}
            alt=""
            className="object-contain aspect-square w-[72px]"
          />
          <div className="mt-2">{label}</div>
        </div>
      </div>
    </div>
  );
};

export default SessionOption;
