/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
    return (
        <header className="flex justify-between items-center px-4 py-6 w-full bg-neutral-900 max-md:max-w-full">
            <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4b7ead5bbd68b16be08f000a11d8756e4f91099498b58d4c478b1b6ba608ac8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
                alt="Company logo"
                className="object-contain self-stretch my-auto aspect-[3.62] w-[152px]"
            />
        </header>
    );
}

export default Header;