/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BackgroundWaves from "./BackgroundWaves";
import { Button, TextField, Typography } from "@mui/material";
import Header from "./Header";
import PasswordResetForm from "./PasswordResetForm";


const PasswordResetPage: React.FC = () => {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <main className="flex flex-col justify-center items-center py-20 bg-background h-screen">
        <section className="flex items-center z-10">
          <div className="flex z-10 flex-col self-center max-md:max-w-full">
            <div className="flex flex-col px-16 py-12 max-w-full rounded-xl bg-neutral-900 max-w-[600px] max-md:px-5">
              <div className="flex flex-col w-full text-center max-md:max-w-full">
                <Typography variant="h3" component="h1" className="text-zinc-200">Password dimenticata?</Typography>
                <Typography variant="body-500" component="p" className="text-gray-400">
                  Inserisci il tuo indirizzo email e ti invieremo un link per
                  resettare la tua password
                </Typography>
              </div>
              <PasswordResetForm />
            </div>
          </div>
          <BackgroundWaves />
        </section>
      </main>
    </div>
  );
};

export default PasswordResetPage;
