/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BackgroundWaves from "../Common/BackgroundWaves";
import { Button, TextField, Typography } from "@mui/material";
import Header from "../Common/Header";
import PasswordResetForm from "./PasswordResetForm";


const PasswordResetPage: React.FC = () => {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <main className="flex flex-col justify-center items-center py-20 px-4 bg-background h-screen">
        <section className="flex z-10 flex-col self-center max-w-[600px] px-6 py-8 md:px-16 md:py-12 rounded-xl bg-neutral-900">
          <div className="flex flex-col text-center gap-2">
            <Typography variant="h3" component="h1" className="text-zinc-200">Password dimenticata?</Typography>
            <Typography variant="body-500" component="p" className="text-gray-400">
              Inserisci il tuo indirizzo email e ti invieremo un link per
              resettare la tua password
            </Typography>
          </div>
          <PasswordResetForm />
        </section>
        <BackgroundWaves />
      </main>
    </div>
  );
};

export default PasswordResetPage;
