/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SignUpForm from "./SignUpForm";
import Header from "../Layout/Header";
import BottomSection from "../Layout/BottomSection";
import BackgroundWaves from "../Layout/BackgroundWaves";


const AuthPage: React.FC = () => {
  return (
    <div className="flex flex-col h-screen">
      <Header leftButton={true} rightButton={false} />
      <main className="flex flex-col justify-center items-center py-20 px-4 bg-background h-screen">
        <section className="flex z-10 flex-col gap-4 self-center max-w-[600px]">
          <SignUpForm />
          <BottomSection title="Hai già un account" buttontext="Fai Login"  />
        </section>
        <BackgroundWaves />
      </main>
    </div>
  );
};

export default AuthPage;
