/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SignUpForm from "./SignUpForm";
import Header from "../Common/Header";
import BackgroundWaves from "../Common/BackgroundWaves";
import RegisterSection from "../Common/BottomSection";

const AuthPage: React.FC = () => {
  return (
    <main className="flex flex-col h-screen">
      <Header />
      <main className="flex flex-col justify-center items-center py-20 px-4 bg-background h-screen">
        <section className="flex z-10 flex-col self-center max-w-[600px] px-6 py-8 md:px-16 md:py-12 rounded-xl bg-neutral-900">
          <SignUpForm />
          <RegisterSection title="Hai già un account" buttontext="Fai Login"  />
        </section>
          <BackgroundWaves />
        </main>
    </main>
  );
};

export default AuthPage;
