/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AuthLayout from "./AuthLayout";
import { Button } from "@mui/material";

const SignUpForm: React.FC = () => {
  return (
    <AuthLayout
      title="Entra a far parte della community"
      subtitle="Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet,"
    >
      <div className="flex flex-col mt-6 w-full max-md:max-w-full">
        <Button
          size="large"
          variant="contained"
          color="primary"
          className="w-full max-md:max-w-full"
        >
          Iscriviti
        </Button>
      </div>
    </AuthLayout>
  );
};

export default SignUpForm;
