/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarItemProps {
  label: string;
  isActive?: boolean;
}

const SidebarItem: React.FC<SidebarItemProps> = ({ label, isActive }) => {
  return (
    <li
      className={`px-6 mt-6 w-full whitespace-nowrap ${
        isActive ? "text-violet-500" : ""
      }`}
    >
      {label}
    </li>
  );
};

export default SidebarItem;
