/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button, Chip, Avatar } from "@/app/mui-components";
import { Typography } from "@mui/material";

export interface ModalMetadataProps {
  lessonCount: number;
  level: string;
  genre: string;
  duration: string;
  instructor: {
    name: string;
    avatarUrl: string;
  };
}

const ModalMetadata: React.FC<ModalMetadataProps> = ({
  lessonCount,
  level,
  genre,
  duration,
  instructor,
}) => {
  return (
    <div className="flex flex-col self-start gap-4">
      <Button
        size="small"
        variant="outlined"
        color="primary"
        className="w-full gap-2"
      >
        <img src="assets/heart.svg" alt="heart" />
        Aggiungi a preferiti
      </Button>
      <MetadataItem label="Numero video">
        <Chip
          label={`${lessonCount} video`}
          size="medium"
          color="primary"
          variant="outlined"
          className="self-start"
          avatar={<Avatar />}
        />
      </MetadataItem>
      <MetadataItem label="Livello">
        <Chip
          label={level}
          size="medium"
          color="primary"
          variant="filled"
          className="self-start"
          avatar={<Avatar />}
        />
      </MetadataItem>
      <MetadataItem label="Genere">
        <Chip
          label={genre}
          size="medium"
          color="primary"
          variant="outlined"
          className="self-start"
        />
      </MetadataItem>
      <MetadataItem label="Durata">
        <Typography variant="caption-500" className="text-text-primary">
          {duration}
        </Typography>
      </MetadataItem>
      <MetadataItem label="Insegnante">
        <div className="flex gap-2 items-center text-text-primary">
          <Avatar  src={instructor.avatarUrl} alt={`${instructor.name}'s avatar`} className="w-8 h-8"/>
          <Typography variant="caption-500">{instructor.name}</Typography>
        </div>
      </MetadataItem>
    </div>
  );
};

interface MetadataItemProps {
  label: string;
  children: React.ReactNode;
}

const MetadataItem: React.FC<MetadataItemProps> = ({ label, children }) => {
  return (
    <div className="flex flex-col gap-2">
      <Typography variant="body-small-500" className="text-text-secondary" component="p">{label}</Typography>
      {children}
    </div>
  );
};

export default ModalMetadata;
