/**
 * This code was generated by Builder.io.
 */

import { Button, Typography } from '@mui/material';

import React from "react";

type BottomSectionProps = {
  title: string;
  buttontext: string;
};

const BottomSection: React.FC<BottomSectionProps> = ({
    title,
    buttontext,
}) => {
  return (
    <section className="flex flex-col gap-2 items-center px-16 py-8 max-w-full rounded-xl bg-neutral-900 w-[600px] max-md:px-5">
      <Typography variant="s1" component="h2" className='text-zinc-200'>
        {title}
      </Typography>
      <Button
        size="large"
        variant="text"
        color="primary"
        className="mt-2 w-full whitespace-nowrap"
      >
        {buttontext}
      </Button>
    </section>
  );
};

export default BottomSection;
