/**
 * This code was generated by Builder.io.
 */
import { Typography } from "@mui/material";
import React from "react";

type EmailSentContentProps = {
  mailfield: boolean;
  title?: string;
  mail?: string;
  description?: string;
  footer?: React.ReactNode;
  imgSrc?: string; 
};

const EmailSentContent: React.FC<EmailSentContentProps> = ({
  mailfield,
  title,
  mail,
  description,
  footer,
  imgSrc,
}) => {
  return (
    <section>
      <div className="flex flex-col text-zinc-200 gap-4">
        <img
          loading="lazy"
          src={imgSrc}
          className="object-contain self-center w-14 aspect-square"
          alt="Email sent icon"
        />
        <div className="flex flex-col gap-2 w-full text-center">
          <Typography variant="h3" component="h1">
            {title}
          </Typography>
          {mailfield && 
            <Typography variant="s1" component="h2">
              {mail}
            </Typography>
          }
          <Typography variant="body-400" component="p" className="text-gray-400">
            {description}
          </Typography>
        </div>
      </div>
      {footer}
    </section>
  );
};


export default EmailSentContent;
