/**
 * This code was generated by Builder.io.
 */
import { Button } from "@mui/material";
import React from "react";
import ChevronLeftFilled from "@mui/icons-material/ChevronLeft";
import ChevronRightFilled from "@mui/icons-material/ChevronRight";

type HeaderProps = {
  leftButton?: boolean;
  rightButton?: boolean;
};

const HeaderOnboarding: React.FC<HeaderProps> = ({
  leftButton,
  rightButton,
}) => {
  return (
    <header className="flex justify-center items-center px-4 py-4 md:py-6 w-full bg-paper z-10 justify-between h-[60px] md:h-[100px]">
      <div className="min-w-[56px] md:w-[136px]">
        {leftButton && (
          <Button
            size="large"
            variant="text"
            color="primary"
            className="flex-1 shrink my-auto w-full px-2"
          >
            <ChevronLeftFilled />
            <span className="hidden md:block">Indietro</span>
          </Button>
        )}
      </div>
      <img
        loading="lazy"
        src="assets/logo.png"
        alt="Company logo"
        className="h-[35px] md:h-[41px] w-auto"
      />
      <div className="min-w-[56px] md:w-[136px]">
        {rightButton && (
          <Button
            size="large"
            variant="text"
            color="primary"
            className="flex-1 shrink my-auto w-full"
          >
            <span className="hidden md:block">Avanti</span>
            <ChevronRightFilled />
          </Button>
        )}
      </div>
    </header>
  );
};

export default HeaderOnboarding;
