/**
 * This code was generated by Builder.io.
 */
"use client"
import theme from "@/app/theme";
import { ArrowDropDownRounded } from "@mui/icons-material";
import { Avatar, Button, IconButton, Link, Menu, MenuItem, Typography } from "@mui/material";
import React from "react";

type HeaderProps = {
  isLogged?: boolean;
};

const Header: React.FC<HeaderProps> = ({
    isLogged,
    }) => {

    const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
    const open = Boolean(anchorEl);
    const handleClick = (event: React.MouseEvent<HTMLElement>) => {
        setAnchorEl(event.currentTarget);
    };
    const handleClose = () => {
        setAnchorEl(null);
    };

    const options = [
    'Option 1',
    'Option 2',
    'Option 3',
    'Option 4',
    ];


    return (
        <header className="flex justify-between items-center px-8 py-6 gap-x-4 w-full bg-paper z-10">
            <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4b7ead5bbd68b16be08f000a11d8756e4f91099498b58d4c478b1b6ba608ac8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
                alt="Company logo"
                className="object-contain self-stretch my-auto aspect-[3.62] w-[152px]"
            />
            <div className="flex gap-x-4">
                <Link className="" underline="none" color="cotrastText" variant="button-l" href={""}>Catalogo</Link>
                <Link className="" underline="none" color="cotrastText" variant="button-l" href={""}>Prezzi</Link>
                <Link className="" underline="none" color="cotrastText" variant="button-l" href={""}>Insegnanti</Link>
                <Link className="" underline="none" color="cotrastText" variant="button-l" href={""}>Percorsi</Link>
                <Link className="" underline="none" color="cotrastText" variant="button-l" href={""}>Aiuto</Link>
            </div>
            <div className="">
                {isLogged ?
                    <div className="flex items-center gap-x-4">
                    <Typography variant="body-400">Mario</Typography>
                    <Avatar
                        sizes="large"
                        alt="Mario"
                        src="https://images.unsplash.com/photo-1508341591423-4347099e1f19?q=80&w=3265&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                        sx={{ border: "1px solid #FF6043"}}
                    />

                    <div>
                        <IconButton
                            aria-label="more"
                            id="long-button"
                            aria-controls={open ? 'long-menu' : undefined}
                            aria-expanded={open ? 'true' : undefined}
                            aria-haspopup="true"
                            onClick={handleClick}
                        >
                            <ArrowDropDownRounded />
                        </IconButton>
                        <Menu
                            id="long-menu"
                            MenuListProps={{
                            'aria-labelledby': 'long-button',
                            }}
                            anchorEl={anchorEl}
                            open={open}
                            onClose={handleClose}
                        >
                            {options.map((option) => (
                            <MenuItem key={option} selected={option === 'Pyxis'} onClick={handleClose}>
                                ciao
                            </MenuItem>
                            ))}
                        </Menu>
                        </div>
                    </div>
                    : 
                    <div className="flex gap-x-4">
                        <Button
                        size="small"
                        variant="outlined"
                        color="primary"
                    >
                        <Typography variant="button-m">Accedi</Typography>
                    </Button>
                    <Button
                        size="small"
                        variant="contained"
                        color="primary"
                    >
                            <Typography variant="button-m">Iscriviti</Typography>
                        </Button>
                    </div>
                }
            </div>
        </header>
    );
}

export default Header;