/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AuthLayout from "../../Common/TopSection";
import { Button } from "@mui/material";
import TopSection from "../../Common/TopSection";

const SignUpForm: React.FC = () => {
  return (
    <TopSection
      title="Entra a far parte della community"
      subtitle="Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet,"
    >
      <div className="flex flex-col w-full">
        <Button
          size="large"
          variant="contained"
          color="primary"
          className="w-full"
        >
          Iscriviti
        </Button>
      </div>
    </TopSection>
  );
};

export default SignUpForm;
