/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InstrumentCard from "./InstrumentCard";
import ProgressIndicator from "./ProgressIndicator";
import { Button } from "@mui/material";
import Layout from "../Layout/Layout";

const instruments = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a9f01c79b578f715b459251417837ada39421f498679215632897a35cb74a861?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Guitar icon",
    name: "Chitarra",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/558487ca2355b45bd61fbc7dc3a5c91d6f085498186a6bf5775f8404e8445ca3?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Drums icon",
    name: "Batteria",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/43fd97e731124e26acb223602590dc8987e8e4c34ef23a88ab50eb66ad69d40c?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Bass icon",
    name: "Basso",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/921aa9828e9a3933467471100fecb692c9b1a2c7ddaa773cc3ed4bbabc64588a?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Ukulele icon",
    name: "Ukulele",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8fc704ae23d18f0b9a1b877ffe6b2982bc865dc95ec174d4d948d3c8bb3fc1ab?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Music production icon",
    name: "Produzione musicale",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9a79385cac6dfd9bee1a13a56b86c76dc2dfd8ff2efb5930e6220f5ebf84dd47?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Piano and keyboard icon",
    name: "Piano e tastiera",
  },
];

const InstrumentSelection: React.FC = () => {
  return (
    <Layout>
      <div className="flex flex-1 gap-2.5 justify-center size-full max-md:max-w-full">
        <div className="flex flex-col justify-between w-[1440px] max-md:max-w-full">
          <header className="flex justify-between items-center self-center px-4 py-6 w-full bg-neutral-900 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2bddc0e67b71b278b176c3f77016a72deb015f9a88a8a58c497f0e00782618c8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
              alt="Company logo"
              className="object-contain self-stretch my-auto aspect-[3.62] w-[152px]"
            />
          </header>
          <section className="flex flex-col flex-1 pt-16 w-full max-md:max-w-full">
            <div className="flex gap-2 items-center self-center">
              <ProgressIndicator active={true} />
              <ProgressIndicator active={false} />
              <ProgressIndicator active={false} />
            </div>
            <div className="flex flex-col justify-center items-center px-8 py-4 mt-6 w-full max-md:px-5 max-md:max-w-full">
              <div className="flex flex-col items-center self-stretch w-full font-semibold text-center max-md:max-w-full">
                <h1 className="text-5xl leading-[58px] text-zinc-200 w-[750px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                  Quale strumento vuoi suonare?
                </h1>
                <p className="mt-4 text-lg leading-7 text-gray-400 w-[700px] max-md:max-w-full">
                  Scegli lo strumento che ti interessa suonare per permetterci
                  di offrirti i contenuti migliori
                </p>
              </div>
              <div className="flex flex-col mt-8 max-w-full w-[650px]">
                <div className="flex flex-wrap gap-4 w-full min-h-[144px] max-md:max-w-full">
                  {instruments.slice(0, 3).map((instrument, index) => (
                    <InstrumentCard key={index} {...instrument} />
                  ))}
                </div>
                <div className="flex flex-wrap gap-4 items-start mt-4 w-full max-md:max-w-full">
                  {instruments.slice(3).map((instrument, index) => (
                    <InstrumentCard key={index + 3} {...instrument} />
                  ))}
                </div>
              </div>
              <Button
                size="large"
                variant="contained"
                color="primary"
                className="mt-8 max-w-full w-[220px]"
                disabled
              >
                Continua
              </Button>
            </div>
          </section>
        </div>
      </div>
    </Layout>
  );
};

export default InstrumentSelection;
