/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InstrumentCardProps {
  imageSrc: string;
  altText: string;
  name: string;
}

const InstrumentCard: React.FC<InstrumentCardProps> = ({
  imageSrc,
  altText,
  name,
}) => {
  return (
    <div className="flex flex-col flex-1 shrink justify-center p-2 rounded-lg basis-0 bg-neutral-900">
      <div className="flex flex-col w-full">
        <div className="flex overflow-hidden flex-col self-end w-4">
          <div className="flex shrink-0 h-4 rounded-full stroke-[2px]" />
        </div>
        <div className="flex flex-col items-center w-full text-base font-semibold whitespace-nowrap text-zinc-200">
          <img
            loading="lazy"
            src={imageSrc}
            alt={altText}
            className="object-contain aspect-square w-[72px]"
          />
          <div className="mt-2">{name}</div>
        </div>
      </div>
    </div>
  );
};

export default InstrumentCard;
