/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ProgressIndicatorProps {
  active: boolean;
}

const ProgressIndicator: React.FC<ProgressIndicatorProps> = ({ active }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center self-stretch my-auto w-[72px]">
      <div
        className={`flex rounded-3xl min-h-[16px] min-w-[24px] w-[72px] ${
          active ? "bg-indigo-500" : "bg-gray-600 bg-opacity-70"
        }`}
      />
    </div>
  );
};

export default ProgressIndicator;
