/**
 * This code was generated by Builder.io.
 */
import { Button } from "@mui/material";
import React from "react";
import ChevronLeftFilled from "@mui/icons-material/ChevronLeft";
import ChevronRightFilled from "@mui/icons-material/ChevronRight";

type HeaderProps = {
  leftButton: boolean;
  rightButton: boolean;
};

const Header: React.FC<HeaderProps> = ({
    leftButton,
    rightButton,
    }) => {
    return (
        <header className="flex justify-center items-center px-4 py-6 w-full bg-header z-10 justify-between h-[100px]">
            <div className="w-[136px]">
                {leftButton &&
                <Button
                    size="large"
                    variant="text"
                    color="primary"
                    className="flex-1 shrink my-auto w-full min-w-[240px] max-md:max-w-full"
                >
                    <ChevronLeftFilled />
                    Indietro
                </Button>
                }
            </div>
            <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/f4b7ead5bbd68b16be08f000a11d8756e4f91099498b58d4c478b1b6ba608ac8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
                alt="Company logo"
                className="object-contain self-stretch my-auto aspect-[3.62] w-[152px]"
            />
            <div className="w-[136px]">
                {rightButton &&
                <Button
                    size="large"
                    variant="text"
                    color="primary"
                    className="flex-1 shrink my-auto w-full min-w-[240px] max-md:max-w-full"
                >
                    Avanti
                    <ChevronRightFilled />
                </Button>
                }
            </div>
        </header>
    );
}

export default Header;