/**
 * This code was generated by Builder.io.
 */
import { Button, Typography } from "@mui/material";
import React from "react";

type TopSectionProps = {
  children?: React.ReactNode;
  title: string;
  subtitle: string;
};

const TopSection: React.FC<TopSectionProps> = ({
  children,
  title,
  subtitle,
}) => {
  return (
    <section className="px-6 py-8 md:px-16 md:py-12 rounded-xl bg-neutral-900">
      <div className="flex flex-col gap-4 w-full text-center mb-6">
        <Typography variant="h3" component="h1" className="text-zinc-200">
          {title}
        </Typography>
        <Typography variant="body-500" component="p" className="text-gray-400">
          {subtitle}
        </Typography>
      </div>
      {children}
    </section>
  );
};

export default TopSection;
