/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const AlphabetFilter: React.FC = () => {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

  return (
    <div className="flex gap-2 justify-center px-5 mt-4 w-full text-2xl font-semibold leading-7 text-center text-black whitespace-nowrap max-w-[1276px] max-md:flex-wrap max-md:max-w-full">
      {alphabet.map((letter) => (
        <button
          key={letter}
          className="flex-1 justify-center p-2 bg-white rounded-lg"
          aria-label={`Filter by letter ${letter}`}
        >
          {letter}
        </button>
      ))}
    </div>
  );
};

export default AlphabetFilter;