/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FeatureCardProps {
  title: string;
  description: string;
  color: string;
  features: string[];
  iconSrc: string;
}

const FeatureCard: React.FC<FeatureCardProps> = ({ title, description, color, features, iconSrc }) => {
  return (
    <div className="flex flex-col grow p-6 w-full font-semibold bg-sky-100 rounded-2xl max-md:px-5 max-md:mt-2">
      <div className="flex flex-col px-4 text-center">
        <div className={`text-4xl leading-10 ${color} uppercase`}>{title}</div>
        <div className="mt-4 text-lg leading-5 text-black">{description}</div>
      </div>
      <div className="flex flex-col justify-center mt-8 text-xl leading-6 text-black">
        {features.map((feature, index) => (
          <div key={index} className="flex gap-4 mt-4 first:mt-0">
            <img loading="lazy" src={iconSrc} alt="" className={`shrink-0 self-start aspect-[1.37] ${color} w-[22px]`} />
            <div className="flex-1">{feature}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default FeatureCard;