/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface Instrument {
  name: string;
  icon: string;
}

const instruments: Instrument[] = [
  { name: 'Chitarra', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/0dc04b172fd748089587f11da7d4be4bcb5a026f8bfd0c9b2014c06648992f5a?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
  { name: 'Batteria', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/ff418ca9bb91b006b3b46be5e73a92e172edf26fed3ce3417fd9432fd64c7514?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
  { name: 'Produzione musicale', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c9c1f06155d8e8bec6d27aac86fcb7be36b04604ab5fda0b8fb074a1d5dfad6b?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
  { name: 'Piano e tastiera', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/3e1256837fc8301151c70583f68fbbe0ed946a4270f03aa85cd89d54e1ed5db5?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
  { name: 'Ukulele', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c15f9f039a96cd29c715bd743f7f2f86ce5f05019995c38f2e41019a74240d2d?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
  { name: 'Basso', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/a566baf76151360eabb33c63e608aa0b2983a5c01c7c3b246bb23cce02ef1a94?apiKey=0d8d667b87194d319b3212d5b3a9fed4&' },
];

const InstrumentFilter: React.FC = () => {
  return (
    <div className="flex gap-4 justify-center px-5 mt-11 w-full text-base font-bold leading-4 text-center text-black max-w-[1276px] max-md:flex-wrap max-md:mt-10 max-md:max-w-full">
      {instruments.map((instrument, index) => (
        <button
          key={index}
          className="flex flex-col flex-1 justify-center px-6 py-4 whitespace-nowrap bg-yellow-50 rounded-2xl max-md:px-5"
        >
          <img
            loading="lazy"
            src={instrument.icon}
            alt={`${instrument.name} icon`}
            className="self-center mix-blend-luminosity aspect-square w-[72px]"
          />
          <div className="mt-4">{instrument.name}</div>
        </button>
      ))}
    </div>
  );
};

export default InstrumentFilter;