/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import FeatureCard from './FeatureCard';
import SubscriptionPlan from './SubscriptionPlan';

const PricingPage: React.FC = () => {
  const features = [
    {
      title: "I CORSI",
      description: "Sono sempre tutti inclusi nell'abbonamento.",
      color: "text-orange-500",
      features: [
        "Lezioni passo-passo",
        "Il catalogo delle lezioni si espande ogni settimana",
        "Difficoltà crescente: da zero, principiante, intermedio, avanzato"
      ],
      iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/fab1298853ac6964f2139710a8e5d8f9e1d73bc8d953955aaa59ab0b14509fbe?apiKey=0d8d667b87194d319b3212d5b3a9fed4&"
    },
    {
      title: "LE MASTERCLASS",
      description: "Lezioni in diretta con interazione insegnante-studenti",
      color: "text-red-600",
      features: [
        "Lezioni di approfondimento",
        "Interviste esclusive",
        "Ottieni le risposte alle tue domande"
      ],
      iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/9af228aa46d72641183d3d2f53cf3ae96b9543cfac6208d619fdfdb206b9f837?apiKey=0d8d667b87194d319b3212d5b3a9fed4&"
    },
    {
      title: "LA COMMUNITY",
      description: "Condividi la tua passione con altri musicisti.",
      color: "text-blue-600",
      features: [
        "Chiedi consigli e confrontati",
        "Richiedi aiuto al nostro corpo docenti",
        "Partecipa alle sfide mensili di Vibly-NOVITÀ"
      ],
      iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/29055a8b6cdfd301dda0ca6073d6b04996fa72672f5d86fec440e96b116d6232?apiKey=0d8d667b87194d319b3212d5b3a9fed4&"
    }
  ];

  return (
    <main className="flex flex-col items-center pb-20 bg-stone-100">
      <Header />
      <h1 className="mt-16 text-6xl font-bold text-center text-black leading-[59.4px] max-md:mt-10 max-md:max-w-full max-md:text-4xl">
        Scegli il piano adatto a te
      </h1>
      <p className="mt-6 text-2xl leading-9 text-center text-black max-md:max-w-full">
        Ecco tutto ciò che mettiamo a disposizione dei nostri studenti iscritti a Vibly
      </p>
      <section className="px-5 mt-11 w-full max-w-[1200px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          {features.map((feature, index) => (
            <div key={index} className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
              <FeatureCard {...feature} />
            </div>
          ))}
        </div>
      </section>
      <section className="flex flex-col px-5 mt-10 max-w-full w-[900px]">
        <SubscriptionPlan
          title="Abbonamento mensile"
          price="€29,99/mese"
        />
        <SubscriptionPlan
          title="Abbonamento TRIMESTRALE"
          price="€8,30/mese"
          isPopular={true}
          discount="-50% sul primo trimestre"
          discountCode="SPRING24TRIM"
        />
        <SubscriptionPlan
          title="Abbonamento ANNUALE"
          price="€11,49/mese"
          discount="-30% sul primo anno"
          discountCode="SPRING24TRIM"
        />
        <p className="mt-4 text-base font-medium leading-4 text-center text-stone-500 max-md:max-w-full">
          Pagamento sicuro. Offerta valida solo per i nuovi abbonati a vibly.tv. Il rimborso non si applica sui rinnovi mensili e annuali.
        </p>
      </section>
    </main>
  );
};

export default PricingPage;