/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SubscriptionPlanProps {
  title: string;
  price: string;
  isPopular?: boolean;
  discount?: string;
  discountCode?: string;
}

const SubscriptionPlan: React.FC<SubscriptionPlanProps> = ({ title, price, isPopular, discount, discountCode }) => {
  return (
    <div className="justify-between p-6 mt-4 bg-white rounded-2xl max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-[57%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col justify-center self-stretch my-auto font-bold max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-col justify-center leading-[140%] max-md:max-w-full">
              {isPopular && (
                <div className="justify-center self-start px-4 py-2 text-sm text-orange-500 uppercase bg-yellow-50 rounded-[40px]">
                  il più scelto
                </div>
              )}
              <div className="mt-1 text-2xl text-black uppercase max-md:max-w-full">{title}</div>
              <div className="mt-1 text-5xl font-semibold text-blue-600 max-md:max-w-full">{price}</div>
            </div>
            {discount && (
              <div className="flex flex-col justify-center mt-3 text-lg leading-5 text-black max-md:max-w-full">
                <div className="justify-center max-md:max-w-full">{discount}</div>
              </div>
            )}
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[43%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow justify-center max-md:mt-10">
            <div className="flex flex-col justify-center font-medium text-black leading-[110%]">
              <div className="flex gap-2 justify-center px-8 text-lg max-md:px-5">
                <div className="shrink-0 my-auto w-3.5 h-3.5 bg-emerald-500 rounded-full" />
                <div>Garanzia di rimborso 30 giorni</div>
              </div>
              <div className="justify-center mt-2 text-base text-center">Disdici quando vuoi</div>
            </div>
            <div className="flex flex-col justify-center mt-4 text-base">
              <div className="flex flex-col justify-center">
                <button className="flex justify-center items-center px-3 py-4 font-medium tracking-wide text-white whitespace-nowrap bg-blue-600 rounded-lg border-2 border-blue-600 border-solid leading-[100%] max-md:px-5">
                  <div className="justify-center px-4">Scegli</div>
                </button>
                <div className="flex flex-col justify-center mt-2 text-center leading-[110%] text-stone-500">
                  <div className="flex flex-col justify-center">
                    <div className="justify-center">Pagamento mensile</div>
                  </div>
                </div>
              </div>
              {discountCode && (
                <div className="flex flex-col justify-center px-3 py-2 mt-4 font-medium tracking-wide text-black border-2 border-black border-solid leading-[100%] rounded-[48px]">
                  <div className="justify-center px-4">CODICE SCONTO: {discountCode}</div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SubscriptionPlan;