/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import InstrumentFilter from './InstrumentFilter';
import AlphabetFilter from './AlphabetFilter';
import TeacherGrid from './TeacherGrid';

const teachers = [
  {
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/b17bb36c845dc436c0e3e522dbd0833982a3448817fd4ba3846d12fedd6a07b7?apiKey=0d8d667b87194d319b3212d5b3a9fed4&",
    name: "Alessandro Barbetti",
    instruments: ["Chitarra"]
  },
  {
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/d16dd4de9905e10348d8f91671787cd9130f36401836959ed6618730b131024d?apiKey=0d8d667b87194d319b3212d5b3a9fed4&",
    name: "Alessandro Bianchi",
    instruments: ["Chitarra", "Basso"]
  },
  {
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/2ed9cb98215b1215db736a0315c4fab7809ed1aae035eaf32734d6e6bb9a884c?apiKey=0d8d667b87194d319b3212d5b3a9fed4&",
    name: "Alessandro Guercini",
    instruments: ["Chitarra"]
  },
  {
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/9c43f874ef8472ddb11c9646e80d02e22644170c32a55afead418ff102f2fe61?apiKey=0d8d667b87194d319b3212d5b3a9fed4&",
    name: "Andrea Cerrato",
    instruments: ["Ukulele"]
  },
  // ... add more teachers here
];

const TeachersPage: React.FC = () => {
  return (
    <div className="flex flex-col items-center pb-16 bg-stone-100">
      <Header />
      <main>
        <h1 className="justify-center px-5 mt-14 text-6xl font-bold text-center text-black leading-[59.4px] max-md:mt-10 max-md:max-w-full max-md:text-4xl">
          I nostri insegnanti
        </h1>
        <p className="mt-6 text-2xl leading-9 text-center text-black">
          Esplora il nostro corpo insegnanti
        </p>
        <InstrumentFilter />
        <AlphabetFilter />
        <section className="px-5 mt-10 w-full max-w-[1276px] max-md:max-w-full">
          <TeacherGrid teachers={teachers} />
        </section>
        <section className="px-5 mt-6 w-full max-w-[1276px] max-md:max-w-full">
          <TeacherGrid teachers={teachers} />
        </section>
        <section className="px-5 mt-6 w-full max-w-[1276px] max-md:max-w-full">
          <TeacherGrid teachers={teachers} />
        </section>
      </main>
    </div>
  );
};

export default TeachersPage;