/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TeacherCardProps {
  imageSrc: string;
  name: string;
  instruments: string[];
}

const TeacherCard: React.FC<TeacherCardProps> = ({ imageSrc, name, instruments }) => {
  return (
    <article className="flex flex-col pb-6 bg-white rounded-2xl">
      <img loading="lazy" src={imageSrc} alt={`${name}'s profile`} className="w-full aspect-[1.41]" />
      <div className="flex flex-col mx-5 mt-6 max-md:mx-2.5">
        <h3 className="text-2xl font-bold leading-6 text-black">{name}</h3>
        <div className="flex gap-2 mt-2 text-xs font-medium tracking-wide leading-5 text-blue-600 whitespace-nowrap">
          {instruments.map((instrument, index) => (
            <span key={index} className="justify-center px-4 py-2 bg-sky-100 rounded-[40px]">
              {instrument}
            </span>
          ))}
        </div>
      </div>
    </article>
  );
};

export default TeacherCard;