/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex z-10 justify-center items-center self-center px-6 mt-4 max-w-full text-base font-semibold whitespace-nowrap text-zinc-200 w-[600px] max-md:px-5">
      <nav className="flex gap-5 justify-between">
        <a href="#">Termini</a>
        <a href="#">Condizioni</a>
      </nav>
    </footer>
  );
};

export default Footer;
