/**
 * This code was generated by Builder.io.
 */
import { Link } from '@mui/material';
import React from "react";


const Footer: React.FC = () => {
  return (
    <footer className="flex z-10 justify-center items-center px-6 mt-4 max-w-full whitespace-nowrap w-[600px] max-md:px-5">
      <nav className="flex gap-5 justify-between max-w-full w-[180px]">
        <Link color="inherit" underline="none">
          Termini
        </Link>
        <Link color="inherit" underline="none">
          Condizioni
        </Link>
      </nav>
    </footer>
  );
};

export default Footer;
