/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex justify-center items-center px-4 py-6 w-full bg-neutral-900 max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a5f7b556c561e4c899d6dba088e58b9933e2c5c5547d93d3d6547de89668aa3f?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
        alt="Vibly logo"
        className="max-w-full aspect-[3.57] w-[152px]"
      />
    </header>
  );
};

export default Header;
