/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import LoginForm from "./LoginForm";
import SignUpPrompt from "./SignUpPrompt";
import Footer from "./Footer";

const LoginPage: React.FC = () => {
  return (
    <main className="flex flex-col justify-center pb-20 bg-zinc-900">
      <Header />
      <LoginForm />
      <SignUpPrompt />
      <Footer />
      <div className="mt-0 w-full bg-indigo-500 min-h-[145px] max-md:mt-0 max-md:max-w-full" />
      <div className="mt-2 w-full bg-indigo-500 min-h-[59px] max-md:max-w-full" />
    </main>
  );
};

export default LoginPage;
