/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LoginForm from "./LoginForm";
import RegisterSection from "./RegisterSection";
import Footer from "./Footer";
import BackgroundWaves from "../Common/BackgroundWaves";
import Header from "../Common/Header";

const LoginPage: React.FC = () => {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <main className="flex flex-col justify-center items-center py-20 px-4 bg-background h-screen">
        <div className="flex z-10 flex-col self-center max-w-[600px] w-full gap-4">
          <LoginForm />
          <RegisterSection />
          <Footer />
        </div>
        <BackgroundWaves />
      </main>
    </div>
  );
};

export default LoginPage;
