/**
 * This code was generated by Builder.io.
 */
import { Button, Checkbox, FormControlLabel, FormLabel, TextField } from '@mui/material';
import React from "react";

const LoginForm: React.FC = () => {
  return (
    <form className="flex flex-col px-16 py-12 max-w-full rounded-xl bg-neutral-900 w-[600px] max-md:px-5">
      <h1 className="self-center text-3xl font-semibold leading-10 text-zinc-200">
        Accedi a Vibly
      </h1>
      <p className="self-center mt-2 text-base font-medium leading-6 text-center text-gray-400">
        Accedi al tuo account
      </p>
      <TextField
        placeholder="Il tuo nome utente o indirizzo email"
        value="Value"
        variant="filled"
        size="medium"
        className="mt-12 max-md:mt-10 max-md:max-w-full"
        InputProps={{}}
        label={
          <FormLabel className="self-start">Nome utente o e-mail</FormLabel>
        }
      />
      <TextField
        placeholder="La tua password"
        value="Value"
        variant="filled"
        size="medium"
        className="mt-6 max-md:max-w-full"
        InputProps={{}}
        label={
          <FormLabel className="self-start whitespace-nowrap">
            Password
          </FormLabel>
        }
      />
      <FormControlLabel
        labelPlacement="end"
        className="mt-4 max-w-full w-[131px]"
        control={<Checkbox size="small" color="primary" checked />} label={undefined}      />
      <Button
        size="large"
        variant="contained"
        color="primary"
        className="mt-8 whitespace-nowrap max-md:max-w-full"
        disabled
      >
        Accedi
      </Button>
      <Button
        size="large"
        variant="text"
        color="primary"
        className="mt-4 max-md:max-w-full"
      >
        Dimenticato la password?
      </Button>
    </form>
  );
};

export default LoginForm;
