/**
 * This code was generated by Builder.io.
 */
import React from "react";

const LoginForm: React.FC = () => {
  return (
    <section className="flex flex-col self-center px-16 py-12 mt-20 max-w-full text-base font-semibold rounded-xl bg-neutral-900 text-zinc-200 w-[600px] max-md:px-5 max-md:mt-10">
      <h1 className="self-center text-3xl leading-10">Accedi a Vibly</h1>
      <p className="self-center mt-2 font-medium text-center text-gray-400 leading-[150%]">
        Accedi al tuo account
      </p>
      <form>
        <label
          htmlFor="username"
          className="block mt-12 leading-[150%] max-md:mt-10 max-md:max-w-full"
        >
          Nome utente o e-mail
        </label>
        <input
          type="text"
          id="username"
          placeholder="Il tuo nome utente o indirizzo email"
          className="p-4 mt-1 w-full text-sm font-medium leading-5 text-gray-400 rounded-lg border border-solid border-neutral-400 max-md:max-w-full"
        />
        <label
          htmlFor="password"
          className="block mt-6 leading-[150%] max-md:max-w-full"
        >
          Password
        </label>
        <div className="flex gap-1.5 p-4 mt-1 text-sm font-medium leading-5 text-gray-400 rounded-lg border border-solid border-neutral-400 max-md:flex-wrap">
          <input
            type="password"
            id="password"
            placeholder="La tua password"
            className="flex-1 bg-transparent border-none outline-none"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/68db9e18a246a87fdc91ae67f096248521db3c2e1f3a132b9ecf749083a7772d?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
            alt=""
            className="shrink-0 self-start aspect-square w-[18px]"
          />
        </div>
        <div className="flex gap-2 self-start mt-4 text-sm leading-4">
          <input
            type="checkbox"
            id="remember"
            className="shrink-0 w-4 aspect-square"
          />
          <label htmlFor="remember">Remember me</label>
        </div>
        <button
          type="submit"
          className="w-full px-8 py-4 mt-8 whitespace-nowrap bg-gray-500 rounded-lg text-neutral-900 max-md:px-5 max-md:max-w-full"
        >
          Accedi
        </button>
      </form>
      <a
        href="#"
        className="block px-8 py-4 mt-4 text-center text-indigo-500 rounded-lg max-md:px-5 max-md:max-w-full"
      >
        Dimenticato la password?
      </a>
    </section>
  );
};

export default LoginForm;
