/**
 * This code was generated by Builder.io.
 */

import { Button } from '@mui/material';
import React from "react";


const RegisterSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center px-16 py-8 mt-4 max-w-full rounded-xl bg-neutral-900 w-[600px] max-md:px-5">
      <h2 className="text-lg font-semibold leading-7 text-center text-zinc-200">
        Non hai un account?
      </h2>
      <Button
        size="large"
        variant="text"
        color="primary"
        className="mt-2 max-w-full whitespace-nowrap w-[189px]"
      >
        Registrati
      </Button>
    </section>
  );
};

export default RegisterSection;
