/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SignUpPrompt: React.FC = () => {
  return (
    <section className="flex flex-col items-center self-center px-16 py-8 mt-4 max-w-full font-semibold rounded-xl bg-neutral-900 w-[600px] max-md:px-5">
      <p className="text-lg leading-7 text-center text-zinc-200">
        Non hai un account?
      </p>
      <a
        href="#"
        className="px-8 py-4 mt-2 max-w-full text-base text-indigo-500 whitespace-nowrap rounded-lg w-[189px] max-md:px-5"
      >
        Registrati
      </a>
    </section>
  );
};

export default SignUpPrompt;
