/**
 * This code was generated by Builder.io.
 */
import { Button, Link, Typography } from "@mui/material";
import React from "react";

const EmailSentContent: React.FC = () => {
  return (
    <section>
      <div className="flex flex-col text-zinc-200 gap-4">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/14a61b52dcf9affb984b46df0908e36c261052a3126939d03a376462dd9d6d3c?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
          className="object-contain self-center w-14 aspect-square"
          alt="Email sent icon"
        />
        <div className="flex flex-col gap-2 w-full text-center">
          <Typography variant="h3" component="h1">
            Email inviata a
          </Typography>
          <Typography variant="s1" component="h2">
            mario.rossi@gmail.com
          </Typography>
          <Typography variant="body-400" component="p" className="text-gray-400">
            Ti abbiamo inviato le istruzioni per resettare la password. Se
            non trovi la mail controlla nella cartella dello spam.
          </Typography>
        </div>
      </div>
      <div className="flex flex-col mt-6 w-full">
        <Button
          size="large"
          variant="contained"
          color="primary"
          className="w-full max-md:max-w-full"
        >
          Torna al login
        </Button>
        <div className="flex flex-wrap items-center gap-1 justify-center mt-8 w-full">
          <small className="text-gray-400 text-body2 font-medium">
            Non hai ricevuto niente?{" "}
          </small>
          <Link
            href="#"
            color="primary"
            underline="none"
            className="font-medium"
          >
            <small>Reinvia la mail</small>
          </Link>
        </div>
      </div>
    </section>
  );
};

export default EmailSentContent;
