/**
 * This code was generated by Builder.io.
 */
import React from "react";
import BottomSection from "@/components/Layout/BottomSection";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";
import TopSection from "@/components/Layout/TopSection";
import { Button } from "@mui/material";
import Layout from "@/components/Layout/LayoutOunboarding";


const AuthPage: React.FC = () => {
  return (
    <Layout headerLeftButton={true}>
      <section className="flex z-10 flex-col gap-4 self-center w-full max-w-[600px]">
        <TopSection title="Entra a far parte della community" subtitle="Condimentum sit nunc in eros scelerisque sed. Commodo in viverra nunc, ullamcorper ut. Non, amet, ">
          <Button
            size="large"
            variant="contained"
            color="primary"
            className="w-full"
          >
            Iscriviti
          </Button>
        </TopSection>
        <BottomSection title="Hai già un account" buttontext="Fai Login"  />
      </section>
      <BackgroundWaves wave="onboardingAuth" />
    </Layout>
  );
};

export default AuthPage;
