/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button, Link } from "@mui/material";
import Layout from "@/components/Layout/Layout";
import Header from "@/components/Layout/Header";
import EmailSentContent from "@/components/Layout/EmailSentContent";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";

const EmailSentPage: React.FC = () => {
  return (
    <Layout>
      <Header leftButton={false} rightButton={false} />
      <main className="flex flex-col justify-center items-center py-20 px-4 bg-background h-screen">
        <section className="flex z-10 flex-col self-center max-w-[600px] px-6 py-8 md:px-16 md:py-12 rounded-xl bg-neutral-900">
          <EmailSentContent 
            title="Email inviata a"
            mailfield={true}
            mail="mario.rossi@gmail.com" 
            description="Ti abbiamo inviato le istruzioni per resettare la password. Se
            non trovi la mail controlla nella cartella dello spam."
            footer={ 
            <div className="flex flex-col mt-6 w-full">
              <Button
                size="large"
                variant="contained"
                color="primary"
                className="w-full max-md:max-w-full"
              >
                Torna al login
              </Button>
              <div className="flex flex-wrap items-center gap-1 justify-center mt-8 w-full">
                <small className="text-gray-400 text-body2 font-medium">
                  Non hai ricevuto niente?{" "}
                </small>
                <Link
                  href="#"
                  color="primary"
                  underline="none"
                  className="font-medium"
                >
                  <small>Reinvia la mail</small>
                </Link>
              </div>
            </div>}
          />
          </section>
          <BackgroundWaves />
        </main>
    </Layout>
  );
};

export default EmailSentPage;
