/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SignUpForm from "./Form/SignUpForm";
import BottomSection from "@/components/Layout/BottomSection";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";
import Layout from "@/components/Layout/LayoutOunboarding";

const SignUpPage: React.FC = () => {
  return (
    <Layout>
      <section className="flex z-10 flex-col gap-4 self-center w-full max-w-[600px]">
        <SignUpForm />
        <BottomSection title="Hai già un account" buttontext="Fai Login" />
      </section>
      <BackgroundWaves wave="onboardingAuth" />
    </Layout>
  );
};

export default SignUpPage;
