/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SignUpForm from "./Form/SignUpForm";
import BottomSection from "@/components/Layout/BottomSection";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";
import Header from "@/components/Layout/Header";
import Layout from "@/components/Layout/Layout";

const SignUpPage: React.FC = () => {
  return (
    <Layout>
      <Header leftButton={false} rightButton={false} />
      <main className="flex flex-col justify-center items-center py-16 px-4 bg-background h-full">
        <section className="flex z-10 flex-col gap-4 self-center w-full max-w-[600px]">
           <SignUpForm />
          <BottomSection title="Hai già un account" buttontext="Fai Login"  />
        </section>
        <BackgroundWaves />
      </main>
    </Layout>
  );
};

export default SignUpPage;
