/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button, Link, Typography } from "@mui/material";
import Layout from "../../Layout/Layout";
import Header from "../../Layout/Header";
import ProgressIndicator from "./Elements/ProgressIndicator";
import ChevronRightFilled from '@mui/icons-material/ChevronRight';
import InstrumentCard from "./Elements/InstrumentCard";

const instruments = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a9f01c79b578f715b459251417837ada39421f498679215632897a35cb74a861?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Guitar icon",
    name: "Chitarra",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/558487ca2355b45bd61fbc7dc3a5c91d6f085498186a6bf5775f8404e8445ca3?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Drums icon",
    name: "Batteria",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/43fd97e731124e26acb223602590dc8987e8e4c34ef23a88ab50eb66ad69d40c?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Bass icon",
    name: "Basso",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/921aa9828e9a3933467471100fecb692c9b1a2c7ddaa773cc3ed4bbabc64588a?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Ukulele icon",
    name: "Ukulele",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8fc704ae23d18f0b9a1b877ffe6b2982bc865dc95ec174d4d948d3c8bb3fc1ab?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Music production icon",
    name: "Produzione musicale",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9a79385cac6dfd9bee1a13a56b86c76dc2dfd8ff2efb5930e6220f5ebf84dd47?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Piano and keyboard icon",
    name: "Piano e tastiera",
  },
];

const InstrumentSelection: React.FC = () => {
  return (
    <Layout>
      <Header leftButton={false} rightButton={false} />
      <main className="py-16 px-4 bg-background h-screen">
        <div className="flex gap-2 mx-auto mb-6 w-[232px]">
          <ProgressIndicator steps={3} currentStep={1} />
        </div>
        <section className="flex flex-col py-4 gap-y-8 items-center max-w-[700px] m-auto text-center">
          <div className="space-y-4">
            <Typography variant="h1" component="h1" className="text-zinc-200">
              Quale strumento vuoi suonare?
            </Typography>
            <Typography variant="s1" component="h2" className="text-gray-400">
              Scegli lo strumento che ti interessa suonare per permetterci
              di offrirti i contenuti migliori
            </Typography>

            {/* da mostrare al go back */}
              <div>
                <Link href="#" underline="none" variant="button-s">
                  Chitarra
                </Link>
                <ChevronRightFilled className="primary h-[16px]" />
                <Link href="#" underline="none" variant="button-s">
                  Acustica
                </Link>
              </div>
            {/* end */}
          </div>

          <div>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 max-w-[600px]">
              {/* Esempio strumento selezionato */}
              {instruments.slice(0, 1).map((instrument, index) => (
                <InstrumentCard key={index} {...instrument} radioValue="a"/>
              ))}
              {instruments.slice(1, 6).map((instrument, index) => (
                <InstrumentCard key={index} {...instrument} radioValue="b"/>
              ))}
            </div>
          
            {/* da mostrare al go back */}
            <div className="flex mx-auto mt-4 gap-2 justify-center w-[40px]">
              <ProgressIndicator steps={2} currentStep={1} />
            </div>
            {/* end */}
          </div>

          <Button
            size="large"
            variant="contained"
            color="primary"
            className="mt-8 max-w-full w-[220px]"
            disabled
          >
            Continua
          </Button>
        </section>
      </main>
    </Layout>
  );
};

export default InstrumentSelection;
