/**
 * This code was generated by Builder.io.
 */
"use client"
import React from "react";
import { Button, IconButton, Link, Step, StepConnector, stepConnectorClasses, StepIconProps, StepLabel, Stepper, styled, Typography } from "@mui/material";
import Layout from "../../Layout/Layout";
import Header from "../../Layout/Header";
import ProgressIndicator from "./Elements/ProgressIndicator";
import ChevronRightFilled from '@mui/icons-material/ChevronRight';
import ArrowBackFilled from '@mui/icons-material/ArrowBack';
import OptionCard from "./Elements/OptionCard";
import theme from "@/app/theme";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";

const QontoConnector = styled(StepConnector)(({ theme }) => ({
  [`& .${stepConnectorClasses.line}`]: {
    display: 'none',
  },
}));

const QontoStepIconRoot = styled('div')<{ ownerState: { active?: boolean } }>(
  ({ theme, ownerState }) => ({
    color: theme.palette.grey[500],
    display: 'flex',
    height: 22,
    alignItems: 'center',
    ...(ownerState.active && {
      color: theme.palette.primary.main,
    }),
    '& .QontoStepIcon-circle': {
      padding: 0,
      width: 72,
      height: 16,
      borderRadius: '10px',
      backgroundColor: 'currentColor',
    },
  }),
);

function QontoStepIcon(props: StepIconProps) {
  const { active, completed, className } = props;

  return (
    <QontoStepIconRoot ownerState={{ active }} className={className}>
      {completed ? (
        <div className="QontoStepIcon-circle" style={{ backgroundColor: theme.palette.primary.main}} />
      ) : (
        <div className="QontoStepIcon-circle" />
      )}
    </QontoStepIconRoot>
  );
}

const steps = ['Select campaign settings', 'Create an ad group', 'Create an ad'];

const instruments = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a9f01c79b578f715b459251417837ada39421f498679215632897a35cb74a861?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Guitar icon",
    name: "Chitarra",
    radioValue: "a",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/558487ca2355b45bd61fbc7dc3a5c91d6f085498186a6bf5775f8404e8445ca3?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Drums icon",
    name: "Batteria",
    radioValue: "b",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/43fd97e731124e26acb223602590dc8987e8e4c34ef23a88ab50eb66ad69d40c?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Bass icon",
    name: "Basso",
    radioValue: "c",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/921aa9828e9a3933467471100fecb692c9b1a2c7ddaa773cc3ed4bbabc64588a?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Ukulele icon",
    name: "Ukulele",
    radioValue: "d",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8fc704ae23d18f0b9a1b877ffe6b2982bc865dc95ec174d4d948d3c8bb3fc1ab?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Music production icon",
    name: "Produzione musicale",
    radioValue: "e",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/9a79385cac6dfd9bee1a13a56b86c76dc2dfd8ff2efb5930e6220f5ebf84dd47?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    altText: "Piano and keyboard icon",
    name: "Piano e tastiera",
    radioValue: "f",
  },
];

const InstrumentSelection: React.FC = () => {
  return (
    <Layout stepsPage={true}>
      {/* Progress Indicator */}
      <div className="flex justify-center items-center gap-x-4">
        <IconButton color="primary" aria-label="back" >
          <ArrowBackFilled />
        </IconButton>
        <Stepper alternativeLabel activeStep={1} connector={<QontoConnector />}>
          {steps.map((label) => (
            <Step key={label}>
              <StepLabel StepIconComponent={QontoStepIcon} />
            </Step>
          ))}
        </Stepper>
        <div className="w-[32px]" />
      </div>
      <section className="flex flex-col py-4 gap-y-8 items-center max-w-[700px] m-auto text-center">
        <div className="space-y-4">
          <Typography variant="h1" component="h1" className="text-zinc-200">
            Quale strumento vuoi suonare?
          </Typography>
          <Typography variant="s1" component="h2" className="text-gray-400">
            Scegli lo strumento che ti interessa suonare per permetterci
            di offrirti i contenuti migliori
          </Typography>

          {/* da mostrare al go back */}
            <div>
              <Link href="#" underline="none" variant="button-s">
                Chitarra
              </Link>
              <ChevronRightFilled fontSize="small" className="text-text-secondary" />
              <Link href="#" underline="none" variant="button-s">
                Acustica
              </Link>
            </div>
          {/* end */}
        </div>

        <div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 max-w-[600px]">
            {/* Esempio strumento selezionato */}
            {instruments.slice(0, 6).map((instrument, index) => (
              <OptionCard key={index} {...instrument}/>
            ))}
          </div>
        
          {/* da mostrare al go back */}
          <div className="flex mx-auto mt-4 gap-2 justify-center w-[40px]">
            <ProgressIndicator steps={2} currentStep={1} />
          </div>
          {/* end */}
        </div>

        <Button
          size="large"
          variant="contained"
          color="primary"
          className="mt-8 max-w-full w-[220px]"
          disabled
        >
          Continua
        </Button>
      </section>
      <BackgroundWaves wave="onboardingSteps" />
    </Layout>
  );
};

export default InstrumentSelection;
