/**
 * This code was generated by Builder.io.
 */
"use client"
import React from "react";
import { styled } from '@mui/material/styles';
import Stepper from '@mui/material/Stepper';
import Step from '@mui/material/Step';
import StepLabel from '@mui/material/StepLabel';
import StepConnector, { stepConnectorClasses } from '@mui/material/StepConnector';
import StepIcon, { StepIconProps } from '@mui/material/StepIcon';
import { Button, IconButton, Typography } from "@mui/material";
import ArrowBackFilled from '@mui/icons-material/ArrowBack';
import OptionCard from "./Elements/OptionCard";
import theme from "@/app/theme";
import BackgroundWaves from "@/components/Layout/BackgroundWaves";
import Layout from "@/components/Layout/Layout";


const QontoConnector = styled(StepConnector)(({ theme }) => ({
  [`& .${stepConnectorClasses.line}`]: {
    display: 'none',
  },
}));

const QontoStepIconRoot = styled('div')<{ ownerState: { active?: boolean } }>(
  ({ theme, ownerState }) => ({
    color: theme.palette.grey[500],
    display: 'flex',
    height: 22,
    alignItems: 'center',
    ...(ownerState.active && {
      color: theme.palette.primary.main,
    }),
    '& .QontoStepIcon-circle': {
      padding: 0,
      width: 72,
      height: 16,
      borderRadius: '10px',
      backgroundColor: 'currentColor',
    },
  }),
);

function QontoStepIcon(props: StepIconProps) {
  const { active, completed, className } = props;

  return (
    <QontoStepIconRoot ownerState={{ active }} className={className}>
      {completed ? (
        <div className="QontoStepIcon-circle" style={{ backgroundColor: theme.palette.primary.main}} />
      ) : (
        <div className="QontoStepIcon-circle" />
      )}
    </QontoStepIconRoot>
  );
}

const steps = ['Select campaign settings', 'Create an ad group', 'Create an ad'];


const levelOptions = [
    {
      name: "Non so suonare lo strumento",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4357711de60ace15a1329694c623073a0fad90aca1bf791988f7f37d55d37718?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
      altText: "Non so suonare lo strumento",
      radioValue: "a",
    },
    {
      name: "So già suonare lo strumento",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/0b5c64df640d04b476d76055832a1c9e3d95b38f82c4aa08138debf237d266f4?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
      altText: "So già suonare lo strumento",
      radioValue: "b",
    },
  ];

  
const LevelSelection: React.FC = () => {  
  return (
    <Layout stepsPage={true}>
      {/* Progress Indicator */}
      <div className="flex justify-center items-center gap-x-4">
        <IconButton color="primary" aria-label="back" >
          <ArrowBackFilled />
        </IconButton>
        <Stepper alternativeLabel activeStep={3} connector={<QontoConnector />}>
          {steps.map((label) => (
            <Step key={label}>
              <StepLabel StepIconComponent={QontoStepIcon} />
            </Step>
          ))}
        </Stepper>
        <div className="w-[32px]" />
      </div>

      <section className="flex flex-col py-4 gap-y-8 items-center max-w-[750px] m-auto text-center">
        {/* Heading */}
        <div className="space-y-4">
          <Typography variant="h1" component="h1" className="text-zinc-200">
            Che percorso vuoi intraprendere?
          </Typography>
          <Typography variant="s1" component="h2" className="text-gray-400">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
          </Typography>
        </div>
        
        {/* Options to select */}
        <div className="grid grid-cols-2 gap-4 max-w-[650px] w-full">
          {/* Esempio sessione selezionat */}
          {levelOptions.slice(0, 4).map((levelOption, index) => (
              <OptionCard key={index} {...levelOption}/>
          ))}
        </div>
        
        <Button
          size="large"
          variant="contained"
          color="primary"
          className="mt-8 max-w-full w-[220px]"
        >
          Continua
        </Button>
      </section>
      <BackgroundWaves wave="onboardingSteps" />
    </Layout>
  );
};

export default LevelSelection;
