/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SessionOption from "./Elements/SessionOption";
import ProgressBar from "./Elements/ProgressBar";
import { Button, IconButton, Typography } from "@mui/material";
import Layout from "@/app/layout";
import Header from "@/components/Layout/Header";
import ArrowBackFilled from '@mui/icons-material/ArrowBack';
import OptionCard from "./Elements/OptionSelectedFeedback";

interface SessionPlannerProps {}

const SessionPlanner: React.FC<SessionPlannerProps> = () => {
  const sessionOptions = [
    {
      id: 1,
      label: "Una volta",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/69bd89def80efb2b72ab9fe83371820acd6488a0bc163b5293acc7fc4cb27ed8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    {
      id: 2,
      label: "Due volte",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a3a2d3aece2819236bfc7721352a53d5f73e830095c71dc92ddd46e3beeaf423?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
      isSelected: true,
    },
    {
      id: 3,
      label: "Tre volte",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/317c0c24912b4e1610c63dc42b60395eb83e3c141da91f0d429c09de36c8700e?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    {
      id: 4,
      label: "Almeno 5",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cd7d1caaee2569dc90b2a868a6c77c4bc9910aca17f2e0eacb54f81a6500fedf?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
  ];

  return (
    <Layout>
      <Header leftButton={false} rightButton={false} />
      <main className="py-16 px-4 bg-background h-screen">
        {/* Progress Indicator */}
        <div className="flex justify-center items-center gap-x-4">
          <IconButton color="primary" aria-label="back" >
            <ArrowBackFilled />
          </IconButton>
          <div className="flex gap-2 w-[232px]">
            <ProgressBar />
          </div>
          <div className="w-[32px]" />
        </div>
        {/* End */}
        <section className="flex flex-col py-4 gap-y-8 items-center max-w-[750px] m-auto text-center">
          {/* Heading */}
          <div className="space-y-4">
            <Typography variant="h1" component="h1" className="text-zinc-200">
              Quante sessioni di studio vuoi organizzare in una settimana?
            </Typography>
            <Typography variant="s1" component="h2" className="text-gray-400">
              Quante volte pensavi di dedicarti a studiare la chitarra
              durante la settimana
            </Typography>
          </div>
          {/* End */}
          
          {/* Options to select */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-[650px]">
              {sessionOptions.map((option) => (
                <SessionOption key={option.id} {...option} />
              ))}
          </div>
          {/* End */}
          
          <Button
            size="large"
            variant="contained"
            color="primary"
            className="mt-8 max-w-full w-[220px]"
          >
            Continua
          </Button>
          
          {/* Feedback once you select the option */}
          <OptionCard
              imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/b6ebe69212335ff31e8c68399faec898376f3fa09436a5debbacbeb0ae729041?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
              text="La maggior parte delle persone sceglie questa opzione"
            />
          {/* End */}
          
        </section>
      </main>
    </Layout>
  );
};

export default SessionPlanner;
