/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SessionOption from "./Elements/SessionOption";
import ProgressBar from "./Elements/ProgressBar";
import { Button } from "@mui/material";

interface SessionPlannerProps {}

const SessionPlanner: React.FC<SessionPlannerProps> = () => {
  const sessionOptions = [
    {
      id: 1,
      label: "Una volta",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/69bd89def80efb2b72ab9fe83371820acd6488a0bc163b5293acc7fc4cb27ed8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    {
      id: 2,
      label: "Due volte",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/a3a2d3aece2819236bfc7721352a53d5f73e830095c71dc92ddd46e3beeaf423?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
      isSelected: true,
    },
    {
      id: 3,
      label: "Tre volte",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/317c0c24912b4e1610c63dc42b60395eb83e3c141da91f0d429c09de36c8700e?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
    {
      id: 4,
      label: "Almeno 5",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cd7d1caaee2569dc90b2a868a6c77c4bc9910aca17f2e0eacb54f81a6500fedf?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438",
    },
  ];

  return (
    <div className="flex overflow-hidden flex-col justify-center items-center bg-zinc-900">
      <div className="flex flex-1 gap-2.5 justify-center size-full max-md:max-w-full">
        <div className="flex flex-col justify-between w-[1440px] max-md:max-w-full">
          <header className="flex justify-between items-center self-center px-4 py-6 w-full bg-neutral-900 max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/141efd544895c57aeba6e244d7e6c496cc8d56616c2cb0f8f5b1ec0b425593ec?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
              alt="Logo"
              className="object-contain self-stretch my-auto aspect-[3.62] w-[152px]"
            />
          </header>
          <main className="flex relative flex-col flex-1 pt-16 w-full max-md:max-w-full">
            <ProgressBar />
            <section className="flex z-0 flex-col justify-center items-center px-8 py-4 mt-6 w-full max-md:px-5 max-md:max-w-full">
              <div className="flex flex-col items-center self-stretch w-full font-semibold text-center max-md:max-w-full">
                <h1 className="text-5xl leading-[58px] text-zinc-200 w-[750px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                  Quante sessioni di studio vuoi organizzare in una settimana?
                </h1>
                <p className="mt-4 text-lg leading-loose text-gray-400 max-md:max-w-full">
                  Quante volte pensavi di dedicarti a studiare la chitarra
                  durante la settimana
                </p>
              </div>
              <div className="flex flex-col mt-8 max-w-full w-[650px]">
                <div className="flex flex-wrap gap-4 w-full min-h-[144px] max-md:max-w-full">
                  {sessionOptions.map((option) => (
                    <SessionOption key={option.id} {...option} />
                  ))}
                </div>
              </div>
              <Button
                size="large"
                variant="contained"
                color="primary"
                className="mt-8 max-w-full w-[220px]"
              >
                Continua
              </Button>
              <div className="flex gap-6 justify-center items-center p-6 mt-8 max-w-full text-lg font-semibold leading-7 rounded-2xl bg-neutral-900 text-zinc-50 w-[450px] max-md:px-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b6ebe69212335ff31e8c68399faec898376f3fa09436a5debbacbeb0ae729041?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
                  alt=""
                  className="object-contain shrink-0 self-stretch my-auto w-12 aspect-[0.72]"
                />
                <p className="flex-1 shrink self-stretch my-auto basis-0">
                  La maggior parte delle persone sceglie questa opzione
                </p>
              </div>
            </section>
            <div className="flex overflow-hidden absolute z-0 flex-col justify-center items-center p-3.5 rounded-lg left-[536px] top-[46px] w-[52px]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/79d94a0c27bd2bbff032848f39ac556b0f4300fa86f70ede94e854650f264fa8?apiKey=ab14136582c84aab8af41f16349d0438&&apiKey=ab14136582c84aab8af41f16349d0438"
                alt=""
                className="object-contain w-full aspect-square"
              />
            </div>
          </main>
        </div>
      </div>
    </div>
  );
};

export default SessionPlanner;
