/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { LoginForm } from "../components/LoginForm";

export const LoginPage: React.FC = () => {
  const handleLogin = (username: string, password: string) => {
    // Handle login logic here
    console.log("Login attempted with:", username, password);
  };

  return (
    <main className="flex flex-col justify-center px-12 py-14 bg-neutral-900 max-w-[549px] max-md:px-5">
      <LoginForm onSubmit={handleLogin} />
    </main>
  );
};
