/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FilterHeader from "./FilterHeader";
import FilterAccordion from "./FilterAccordion";
import LevelSlider from "./LevelSlider";
import { Checkbox, FormControlLabel, FormGroup } from "@mui/material";

const FilterContainer: React.FC = () => {
  return (
    <section className="flex flex-col rounded-xl bg-paper min-w-[264px] py-6 gap-6">
      <FilterHeader />
        <FilterAccordion title="Tipo chitarra">
          <FormGroup>
            {[
            "Elettrica",
            "Acustica",
            ].map((label, index) => (
            <FormControlLabel
                key={index}
                label={label}
                control={<Checkbox />}
            />
            ))}
          </FormGroup>
        </FilterAccordion>
        <LevelSlider />
        <div>
          <FilterAccordion title="Genere">
            <FormGroup>
              {[
              "Rock",
              "Blues",
              "Pop",
              "Metal",
              "Jazz-fusion",
              "Funk",
              "Hip Hop",
              "Pop",
              ].map((label, index) => (
              <FormControlLabel
                  key={index}
                  label={label}
                  control={<Checkbox />}
              />
              ))}
            </FormGroup>
          </FilterAccordion>
          <FilterAccordion title="Argomento">
            <FormGroup>
              {[
              "Argomento 1",
              "Argomento 2",
              "Argomento 3",
              ].map((label, index) => (
              <FormControlLabel
                  key={index}
                  label={label}
                  control={<Checkbox />}
              />
              ))}
            </FormGroup>
          </FilterAccordion>
        </div>
    </section>
  );
};

export default FilterContainer;
