/**
 * This code was generated by Builder.io.
 */
import { Typography } from "@mui/material";
import React from "react";

const FilterHeader: React.FC = () => {
  return (
    <header className="px-6">
      <Typography variant="h3" component="h3">Filtri</Typography>
    </header>
  );
};

export default FilterHeader;
